### ISSUE TITLE
How to install this ?

### ISSUE THREAD

**Issue by bheemreddy181-zz** [foora/grafana-api-datasource#3]

**Comment by foora** [comment]
you can download zip from thie repository and unzip to /var/lib/grafana/plugins

**Comment by bheemreddy181-zz** [comment]
Can you update the readme accordingly ?

**Comment by bheemreddy181-zz** [comment]
And is there a way we can skip the /test endpoint for configuring this ?

**Comment by bheemreddy181-zz** [comment]
@foora when ever you get a chance , can you take a look at the above question ?

**Comment by foora** [comment]
@bheemreddy181 I have updated the readme.

> And is there a way we can skip the /test endpoint for configuring this ?


Maybe I will add a debug mode which can't skip the /test endpoint  in the future. But the debug 
mode just be used to develop. it is still closed in release version.
Now if you want to skip the /test endpoint, you can Modify code in /src/datasource.js and build your own version.(**I don't suggest this in production env**)
```
// modify testDatasource method
testDatasource() {
    return Promise.resolve({ status: 'success', message: 'Data source is working', title: 'Success' });
}
```
