### ISSUE TITLE
Need help with the setup

### ISSUE THREAD

**Issue by bheemreddy181-zz** [foora/grafana-api-datasource#4]
Here are things is commented out for /test endpoint to work
<img width="1099" alt="Screen Shot 2020-05-16 at 21 46 32" src="https://user-images.githubusercontent.com/3464623/82134622-1c71f700-97bf-11ea-853c-21d8e140771e.png">
<img width="1386" alt="Screen Shot 2020-05-16 at 21 46 39" src="https://user-images.githubusercontent.com/3464623/82134623-1da32400-97bf-11ea-97ce-8c758d54506b.png">

I was unziped it into the plugins folder as you suggested as below
<img width="1050" alt="Screen Shot 2020-05-16 at 21 46 04" src="https://user-images.githubusercontent.com/3464623/82134629-2e539a00-97bf-11ea-9af7-3eb450e1fe4c.png">

But still the query inspector doesn't load up 

<img width="1664" alt="Screen Shot 2020-05-16 at 21 45 42" src="https://user-images.githubusercontent.com/3464623/82134635-3b708900-97bf-11ea-8cd1-fb9260bf81b0.png">

Is there anything i am missing

**Comment by bheemreddy181-zz** [comment]
This is what i see in the logs 

```
bvennapureddy@clm-C02TT0U0HTDG ~/grafana-api-datasource (master) $ tail -f /usr/local/var/log/grafana/grafana.log
t=2020-05-16T21:38:44-0500 lvl=info msg="Initializing UsageStatsService" logger=server
t=2020-05-16T21:38:44-0500 lvl=info msg="Initializing CleanUpService" logger=server
t=2020-05-16T21:38:44-0500 lvl=info msg="Initializing NotificationService" logger=server
t=2020-05-16T21:38:44-0500 lvl=info msg="Initializing provisioningServiceImpl" logger=server
t=2020-05-16T21:38:44-0500 lvl=info msg="Backend rendering via phantomJS" logger=rendering renderer=phantomJS
t=2020-05-16T21:38:44-0500 lvl=warn msg="phantomJS is deprecated and will be removed in a future release. You should consider migrating from phantomJS to grafana-image-renderer plugin. Read more at https://grafana.com/docs/grafana/latest/administration/image_rendering/" logger=rendering renderer=phantomJS
t=2020-05-16T21:38:44-0500 lvl=info msg="Initializing Stream Manager"
t=2020-05-16T21:38:44-0500 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2020-05-16T21:39:44-0500 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/2/search remote_addr=[::1] referer="http://localhost:3000/dashboard/new?orgId=1&gettingstarted" error="http: proxy error: dial tcp: lookup codecov.com: no such host"
t=2020-05-16T21:39:44-0500 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/2/search status=502 remote_addr=[::1] time_ms=86 size=0 referer="http://localhost:3000/dashboard/new?orgId=1&gettingstarted"
```

**Comment by foora** [comment]
this is an bug. I have fix it. 
You can install the new release version(use grafana-cli  to install plugins. the install command I have updated in readme)

**Comment by bheemreddy181-zz** [comment]
Can I still ignore the /test as I did above @foora ?

**Comment by foora** [comment]
Can still use this way.
But when query Inspector in the dashboard, the server which you provide when adding datasource must be exist.

**Comment by bheemreddy181-zz** [comment]
Got it thanks :)
